# Generated by Django 6.0.1 on 2026-01-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_link', models.CharField(default='@tapteacher', help_text='YouTube Link or Username', max_length=255)),
                ('telegram_link', models.CharField(default='https://t.me/tapteacher', help_text='Telegram Link or Username', max_length=255)),
            ],
        ),
    ]
