# Generated by Django 6.0.1 on 2026-01-07 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('govt', 'Government School'), ('semi', 'Semi-Government School'), ('private', 'Private School'), ('coaching', 'Private Coaching & Tution')], max_length=50)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('belief', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_link', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='core.institute')),
            ],
        ),
        migrations.CreateModel(
            name='VacancyPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('prt', 'PRT'), ('tgt', 'TGT'), ('pgt', 'PGT'), ('other', 'Other')], max_length=20)),
                ('subject', models.CharField(max_length=100)),
                ('qualification', models.TextField(blank=True, default='NA')),
                ('compensation', models.TextField(blank=True, default='NA')),
                ('eligibility', models.TextField(blank=True, default='NA')),
                ('age_limit', models.TextField(blank=True, default='NA')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='core.vacancy')),
            ],
        ),
    ]
