# Generated by Django 6.0.1 on 2026-01-07 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_institute_vacancy_vacancypost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('saved', 'Saved for Later')], default='applied', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('vacancy_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.vacancypost')),
            ],
            options={
                'unique_together': {('user', 'vacancy_post', 'status')},
            },
        ),
    ]
