# Generated by Django 6.0.1 on 2026-01-07 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapplication',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('saved', 'Saved for Later'), ('not_interested', 'Not Interested')], default='applied', max_length=20),
        ),
    ]
