# Generated by Django 6.0.1 on 2026-01-10 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_guidancecategory_guidancesubject_guidancetopic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20)),
                ('dob', models.DateField()),
                ('unique_number', models.CharField(blank=True, max_length=50)),
                ('additional_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('highest_qual_desc', models.TextField(blank=True)),
                ('highest_qual_file', models.FileField(blank=True, null=True, upload_to='verification/qualifications/')),
                ('edu_cert_desc', models.TextField(blank=True)),
                ('edu_cert_file', models.FileField(blank=True, null=True, upload_to='verification/certificates/')),
                ('exp_desc', models.TextField(blank=True)),
                ('exp_file', models.FileField(blank=True, null=True, upload_to='verification/experience/')),
                ('expected_salary', models.CharField(blank=True, max_length=100)),
                ('salary_statement_file', models.FileField(blank=True, null=True, upload_to='verification/salary/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
