# Generated by Django 6.0.1 on 2026-01-10 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_userverification_dob_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuidanceTopicFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='guidance/files/')),
                ('file_type', models.CharField(choices=[('ppt', 'PPT'), ('pdf', 'PDF'), ('image', 'Image')], default='other', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.guidancetopic')),
            ],
        ),
    ]
