# Generated by Django 6.0.1 on 2026-01-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_guidancetopicfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userverification',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='verification/resumes/'),
        ),
    ]
