# Generated by Django 6.0.1 on 2026-01-11 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userverification',
            name='last_syllabus_visit',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
