# Generated by Django 6.0.1 on 2026-02-11 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_userreadvacancy'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('prt', 'PRT'), ('tgt', 'TGT'), ('pgt', 'PGT'), ('other', 'Other')], max_length=20)),
                ('subject', models.CharField(help_text='e.g. Physics, Mathematics', max_length=100)),
                ('email_subject', models.CharField(help_text='Subject line for the email', max_length=255)),
                ('email_body', models.TextField(help_text='Body content for the email')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('category', 'subject')},
            },
        ),
    ]
