# Generated by Django 6.0.1 on 2026-03-14 01:20

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_emailtemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, storage=core.models.get_raw_storage, upload_to='chat_attachments/'),
        ),
        migrations.AlterField(
            model_name='guidancetopic',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, storage=core.models.get_raw_storage, upload_to='guidance/pdfs/'),
        ),
        migrations.AlterField(
            model_name='guidancetopic',
            name='ppt_file',
            field=models.FileField(blank=True, null=True, storage=core.models.get_raw_storage, upload_to='guidance/ppts/'),
        ),
        migrations.AlterField(
            model_name='guidancetopicfile',
            name='file',
            field=models.FileField(storage=core.models.get_raw_storage, upload_to='guidance/files/'),
        ),
        migrations.AlterField(
            model_name='userverification',
            name='edu_cert_file',
            field=models.FileField(blank=True, null=True, storage=core.models.get_raw_storage, upload_to='verification/certificates/'),
        ),
        migrations.AlterField(
            model_name='userverification',
            name='exp_file',
            field=models.FileField(blank=True, null=True, storage=core.models.get_raw_storage, upload_to='verification/experience/'),
        ),
        migrations.AlterField(
            model_name='userverification',
            name='highest_qual_file',
            field=models.FileField(blank=True, null=True, storage=core.models.get_raw_storage, upload_to='verification/qualifications/'),
        ),
        migrations.AlterField(
            model_name='userverification',
            name='resume',
            field=models.FileField(blank=True, null=True, storage=core.models.get_raw_storage, upload_to='verification/resumes/'),
        ),
        migrations.AlterField(
            model_name='userverification',
            name='salary_statement_file',
            field=models.FileField(blank=True, null=True, storage=core.models.get_raw_storage, upload_to='verification/salary/'),
        ),
    ]
