# Generated by Django 6.0.1 on 2026-03-29 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_chatmessage_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userverification',
            name='location_preferences',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
