# Generated by Django 6.0.1 on 2026-03-30 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_userverification_location_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='userverification',
            name='alert_engagement_score',
            field=models.IntegerField(default=0, help_text='Number of times user explicitly applied to jobs.'),
        ),
        migrations.AddField(
            model_name='userverification',
            name='viewed_vacancies',
            field=models.ManyToManyField(blank=True, help_text='Jobs proactively viewed before alert sending.', related_name='viewed_by_users', to='core.vacancypost'),
        ),
    ]
