# Generated by Django 6.0.1 on 2026-03-30 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_userverification_alert_engagement_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancypost',
            name='alert_emails_sent',
            field=models.BooleanField(default=False, help_text='Checked if daily alert script has already processed this post.'),
        ),
    ]
