# Generated by Django 6.0.1 on 2026-05-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_emailtemplate_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancypost',
            name='total_posts',
            field=models.CharField(blank=True, default='', help_text='Number of vacancies', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vacancypost',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
