# Generated by Django 6.0.1 on 2026-05-29 12:10

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_mcq_and_notes_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SentEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('email_type', models.CharField(max_length=50)),
                ('recipient', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterModelOptions(
            name='guidancetopic',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.CreateModel(
            name='AnswerWritingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_writing_questions', to='core.guidancetopic')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerWritingSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_file', models.FileField(storage=core.models.get_raw_storage, upload_to='answer_writing/submissions/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('remark_text', models.TextField(blank=True, null=True)),
                ('remark_file', models.FileField(blank=True, null=True, storage=core.models.get_raw_storage, upload_to='answer_writing/remarks/')),
                ('remarked_at', models.DateTimeField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.answerwritingquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('question', 'user')},
            },
        ),
    ]
